### ISSUE TITLE
Add Path Error

### ISSUE THREAD

**Issue by davewolfe-asti** [microsoft/setup-msbuild#42]
Getting an error that the Add-Path option is deprecated, and that environment variables should be used. I'm new to using GitHub actions so some of the examples I'm looking at are breaking.

**Comment by timheuer** [comment]
Hi @davewolfe-asti this is a dupe of #26 and has been resolved in latest version if you change to that.

**Comment by imba-tjd** [comment]
Hi @timheuer I'm still getting this error. As you can see I'm using `@master`

```
Run microsoft/setup-msbuild@master
  with:
C:\ProgramData\Chocolatey\bin\vswhere.exe -products * -requires Microsoft.Component.MSBuild -property installationPath -latest
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
Error: Unable to process command '::add-path::C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands
```

The script is https://github.com/imba-tjd/build-miengine/blob/master/.github/workflows/build.yml

**Comment by timheuer** [comment]
@imba-tjd Don't use the '@master' versioning on Actions -- always use a version/hash/tag -- as you note using the appropriate version per the documentation works.
